# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# 仮免問題作成
# 画像あり
# Problem.create(question_image_url: "",question_text: "", explanation: "", correct_answer: )
# 画像なし
# Problem.create(question_text: "", explanation: "", correct_answer: )

# 本免許問題
# 画像あり
# Problem.create(question_image_url: "",question_text: "", explanation: , correct_answer: "", karimen: false)
# 画像なし
# Problem.create(question_text: "", explanation: "", correct_answer: , karimen: false)

Problem.create(question_text: "原動機付自転車が交差点を右折するときは、あらかじめできるだけ道路の中央により、交差点の中心のすぐ内側を徐行しながら通行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "車に乗るときは、自分で必ず車の死角を確かめることが大切であるが、車の下まで見る必要はない。", explanation: "周囲の確認とともに、車の下まで確認をします。", correct_answer: false)
Problem.create(question_text: "車両通行帯境界線が黄色の線で区画されているときは、たとえ右折、左折のためであっても黄色の線をこえて進路を変更してはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "対面する信号が赤色の灯火の点滅をしているときは、車は停止位置で一時停止をしたうえで、他の交通に注意して進まなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交通整理中の警察官が、身体の正面に平行して振っている灯火を頭上に上げたときの灯火による信号の意味は、その警察官の身体の正面に対面する交通については、信号機の黄色の信号と同じ意味である。", explanation: "警察官の身体の正面に対面する交通については、赤信号と同じ意味です。", correct_answer: false)
Problem.create(question_text: "仮免許による運転において、同乗指導を行う者の座席の位置は、特に定められていない。", explanation: "仮免許で、運転練習をするときは、運転者席の横に乗せてその指導を受けなければなりません。", correct_answer: false)
Problem.create(question_text: "一時停止の道路標識に従って停止すれば、交差点の右方からの交通に対しては優先して通行することができる。", explanation: "停止線の直前で一時停止をし、交差する道路を通行している車や路面電車の進行を妨げてはいけません。", correct_answer: false)
Problem.create(question_text: "オートマチック車は、運転中信号待ちで停止しているときは、ブレーキを踏んでいるか、セレクトレバー（チェンジレバー）をニュートラルレンジ（Ｎ）の位置に入れていればクリープ現象を防ぐことができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "二輪車を押して歩いていれば、たとえエンジンがかかっていても歩行者として扱われる。", explanation: "エンジンをかけているもの、側車付、けん引しているものを押しているときは歩行者として扱われません。", correct_answer: false)



Problem.create(question_text: "交通違反により免許の効力が停止されている場合に運転すると、免許証不携帯違反となる。", explanation: "免許証不携帯違反ではなく無免許運転となります", correct_answer: false)
Problem.create(question_text: "児童の乗り降りのため停止している通学・通園バスの側方を通過するときは、バスとの間に1メートル以上の間隔が取れれば徐行しくてもよい。", explanation: "通学・通園バスのそばを通るときは、徐行して安全を確かめなければなりません。", correct_answer: false)
Problem.create(question_text: "ガソリンスタンドに入ろうとしたとき、歩道上に歩行者がいなかったので徐行して横切った。", explanation: "歩行者がいてもいなくても歩道や路側帯を横切るときは、その直前で一時停止をしなければなりません。", correct_answer: false)
Problem.create(question_text: "道路外に出るため左折するときは、徐行しなくてもよい。", explanation: "道路外へ左折しようとするときは、あらかじめできるだけ道路の左端に　よって徐行しなければなりません。 ", correct_answer: false)
Problem.create(question_text: "交通整理の行われていない横断歩道やその手前で停止している車があるときは、そのそばを通って前方に出る前に、一時停止か徐行しなければならない。", explanation: "停止している車のそばを通って前方に出る前に一時停止をします。", correct_answer: false)
Problem.create(question_text: "仮免許で運転練習中交通事故を起こしたり交通違反をすると、仮免許の停止処分を受ける。", explanation: "交通違反をすると、６点で取消しとなり、停止処分はありません。", correct_answer: false)
Problem.create(question_text: "制動距離は、空走距離と停止距離を合わせたものである。", explanation: "制動距離とは、ブレーキがきき始めてから停止するまでに車の走る距離のことです。", correct_answer: false)
Problem.create(question_text: "踏切を通過するときは、踏切内でエンストしないためにすばやく変速操作をし、速やかに通過する。", explanation: "踏み切り上では、変速操作をしてはいけません。", correct_answer: false)
Problem.create(question_text: "一方通行の道路から右折するときは、あらかじめできるだけ道路の中央により、交差点の中心の内側を徐行しなければならない。", explanation: "あらかじめできるだけ道路の右端により、交差点の中心の内側を徐行しながら通行しなければなりません。", correct_answer: false)
Problem.create(question_text: "歩行者が進路前方の横断歩道を横断しようとしていたので、徐行して道をゆずった。", explanation: "歩行者や自転車が横断歩道を横断しているときや、横断しようとしているときは、必ず一時停止しなければなりません。", correct_answer: false)
Problem.create(question_text: "道路の左側部分が6メートルの道路で追い越をするときは、中央線からそのはみ出し方を必要最小限度にして通行しなければならない。", explanation: "左側部分の幅が６メートル以上ある道路では、右側部分にはみ出して追い越しをしてはいけません。", correct_answer: false)
Problem.create(question_text: "運転免許試験に合格すれば、免許証交付前に運転しても無免許運転にはならない。", explanation: "免許試験に合格しても、免許証交付前に運転すると無免許運転となります。", correct_answer: false)
Problem.create(question_text: "歩行者用道路を許可を受けて通行するとき、歩行者がいなかったので徐行せずに通行した。", explanation: "歩行者がいるいないにかかわらず歩行者に注意して徐行しなければなりません。", correct_answer: false)
Problem.create(question_text: "中央線が黄色でひかれている道路で、バスが乗降客のため停車しているときは、道路の右側部分にはみ出さないと通行できないので、後方でバスが発進するまで待たなければならない。", explanation: "黄色の中央線は、「追い越しのための右側部分はみ出し通行禁止」であり、駐停車中の車は障害物と同じなので側方通過して通行できます。", correct_answer: false)
Problem.create(question_text: "車の種類を特定する場合の略称で「マイクロバス」とは、乗車定員10人以上30人未満の大型乗用自動車をさしている。", explanation: "「マイクロバス」とは、乗車定員１１人以上３０人未満（１１人以上２９人以下）の大型バス以外の大型乗用自動車および特定中型乗用自動車です。", correct_answer: false)
Problem.create(question_text: "勾配の急な下り坂は追い越しを禁止する場所ではない。", explanation: "勾配の急な下り坂は追い越し禁止場所です。", correct_answer: false)
Problem.create(question_text: "安全な車間距離とは、制動距離と同じ程度の距離をいう。", explanation: "安全な車間距離は、停止距離と同程度かそれ以上の距離です。", correct_answer: false)
Problem.create(question_text: "交通規則は、交通事故をなくし、道路を安全に通行できるように定められているが、交通公害を防止することまでは定められていない。", explanation: "道路交通によって起きる障害（交通公害）の防止を図る事も定められています。", correct_answer: false)
Problem.create(question_text: "仮免許で路上練習をする場合は、車の前か後の地上０．４メートル以上１．２メートル以下の見やすい位置へ「初心運転者標識」（初心者マーク）をつけなければならない。", explanation: "車の前と後の定められた位置に「仮免許練習標識」を付けなければなりません。", correct_answer: false)
Problem.create(question_text: "運転免許試験に合格すれば、免許証交付前に自動車を運転しても無免許運転にはならない。", explanation: "試験に合格しても、免許証交付前に自動車を運転をすると無免許運転になります。", correct_answer: false)
Problem.create(question_text: "中央線が黄色の場合は、追い越しも追い抜きも禁止されている。", explanation: "黄色の中央線は「追い越しのための右側部分はみ出し通行禁止」なのではみ出さなければ追い越しも追い抜きもできます。", correct_answer: false)
Problem.create(question_text: "道路標識の補助標識に用いられる車両の略称で「大貨等」とは、大型貨物自動車と普通貨物自動車を表している。", explanation: "「大貨等」とは、大型貨物自動車と特定中型貨物自動車、大型特殊自動車を表しています。", correct_answer: false)
Problem.create(question_text: "一時停止の標識のあるところでは、停止線があればその直前で、停止線がないときは標識の直前で停止しなければならない。", explanation: "停止線がないときは、交差点の直前で停止します。", correct_answer: false)
Problem.create(question_text: "道路に面した場所に入るため、歩道や路側帯を横切るときは、歩行者がいなければ徐行して進んでよい。", explanation: "歩道や路側帯を横切るときは、歩行者の有無に関係なくその直前で一時停止をします。", correct_answer: false)
Problem.create(question_text: "交差点で警察官が手信号による信号をしているときの停止位置は、その警察官の１メートル手前である。", explanation: "交差点では、その直前（交差点のすぐ近くに横断歩道や自転車横断帯があるところでは、その直前。", correct_answer: false)
Problem.create(question_text: "障害物をよける場合に行う合図は、その行為を行う３０メートル手前である。", explanation: "障害物をよけるということは、進路変更になるので合図の時期は３秒前になります。", correct_answer: false)
Problem.create(question_text: "車両横断禁止の標識のある道路でも、道路の右側に面した場所に自分の車庫があるときは、右折して入ることができる。", explanation: "たとえ右側に面した場所に自分の車庫がある場合でも横断してはいけません。", correct_answer: false)
Problem.create(question_text: "踏み切りで故障したため外に移動させていたら、警報機が鳴り出したのでいそいで踏切支障報知装置を使用した。", explanation: "①知らせる。踏切支障報知装置（非常ボタン）を押す。発炎筒、煙の出るもの。②移動する。③近くの駅に連絡するの順序です。", correct_answer: false)
Problem.create(question_text: "「警笛鳴らせ」の標識の無いところでも、山道や左右の見通しの悪い交差点は、危険な場所であるから警笛を使って走行する。", explanation: "警音器は、指定された場所以外は、みだりに警音器を鳴らしてはいけません。しかし危険を避けるためなら鳴らすことができます。　", correct_answer: false)
Problem.create(question_text: "勾配の急な上り坂は、徐行場所なので追い越しをしてはならない。", explanation: "勾配の急な上り坂は徐行場所ではなく、追い越しも禁止されていません。", correct_answer: false)
Problem.create(question_text: "交差点を右折しようとして自分が先に交差点に入ったときは、その交差点を直進する車より先に進行することができる。", explanation: "先に交差点に侵入しても直進車、左折車が優先しますのでその通行を妨げてはいけません。", correct_answer: false)
Problem.create(question_text: "仮免許を受けた者が道路で運転練習をするときの同乗指導者は、第一種免許を受けて３年以上の経験者であれば、その免許の種類に関係なく同乗指導を行うことができる。", explanation: "同乗指導のできる条件は、①指定自動車教習所の教習指導員　②その車を運転できる第一種免許３年以上受けている人　③その車を運転できる第二種免許を受けている人に限られます。", correct_answer: false)
Problem.create(question_text: "安全地帯は、歩行者がいるときに限り乗り入れてはならない。", explanation: "車は、安全地帯には絶対に入ることはできません。", correct_answer: false)
Problem.create(question_text: "小型特殊免許で運転することのできる車は、小型特殊自動車と原動機付自転車である。", explanation: "小型特殊免許では、原動機付自転車は運転できません。", correct_answer: false)
Problem.create(question_text: "普通免許を受けた者が、免許証を持たないで普通自動車を運転した場合は、無免許運転となる。", explanation: "免許証を持たないで運転すると「無免許運転」ではなく、「免許証不携帯」違反となります。", correct_answer: false)
Problem.create(question_text: "歩行者用道路を通行する場合は、歩行者がいれば徐行して通るが、歩行者がいない場合は、徐行する必要がない。", explanation: "特に通行を認められた車が、通行できますが特に歩行者に注意して通行しなければなりません。（歩行者がいるいないにかかわらず徐行です。）", correct_answer: false)
Problem.create(question_text: "幼児を乗せる場合、後部座席では目が届かなく危険であるので、前の座席に乗せなくてはいけない。", explanation: "交通事故の被害を軽減、運転操作の支障となることを防止するため、後部座席に取り付けましょう。", correct_answer: false)
Problem.create(question_text: "バスの停留所付近は危険な場所であるため、バス停の表示板から１０メートル以内は、運行時間内に限り徐行しなければならない。", explanation: "バスの停留所付近は運行時間内でも徐行する必要はありません。", correct_answer: false)
Problem.create(question_text: "空走距離とは、ブレーキが効き始めてから、車が停止するまでの距離をいう。", explanation: "空走距離とは、ハッと思ってブレーキを踏みブレーキが効き始めるまでの走る距離のことをいいます。", correct_answer: false)
Problem.create(question_text: "歩道や路側帯を横切るときは、歩行者がいるいないにかかわらず徐行か一時停止をしなければならない。", explanation: "歩道や路側帯を横切るときは、必ず一時停止をします。（歩行者がいるいないに関係なく）", correct_answer: false)
Problem.create(question_text: "追い越しをしようとするときは、まず方向指示器を出してから後方の安全を確かめるとよい。", explanation: "追い越しの手順は、前方の安全を確かめるとともに、バックミラーなどで後方の確認をしてから合図を出します。", correct_answer: false)
Problem.create(question_text: "原動機付自転車でも、後ろに座席をつければ２人乗りすることができる。", explanation: "原動機付自転車は２人乗りは禁止です。", correct_answer: false)
Problem.create(question_text: "交通規則を守っている以上、自分の権利を主張すべきで、譲り合う必要はない。", explanation: "車を運転するときは、相手の立場になりゆずりあい、思いやりを持って運転をしましょう。", correct_answer: false)
Problem.create(question_text: "道路に面した場所に出入りするため歩道や路側帯を横切るときは、歩行者の有無に関係なく徐行しなければならない。", explanation: "歩道や路側帯を横切るときは、必ず一時停止をしなければなりません。", correct_answer: false)
Problem.create(question_text: "運転中に、バックミラーをたびたび見るとのろのろ運転となり、交通渋滞の原因となるのであまり見ないほうがよい。", explanation: "走行中もバックミラー等で後方の状況も確認しなければなりません。", correct_answer: false)
Problem.create(question_text: "一般道路における660ｃｃ以下の普通貨物自動車の最高速度は、５０キロメートル毎時である。", explanation: "660ｃｃ以下の普通貨物自動車の最高速度は、６０キロメートル毎時です。", correct_answer: false)
Problem.create(question_text: "信号機の信号が黄色の灯火の点滅をしているときは、一時停止か徐行しなければならない。", explanation: "黄色の灯火の点滅信号は、歩行者や車は他の交通に注意して進むことができます。", correct_answer: false)
Problem.create(question_text: "車は、子供が一人で歩いているときや、白や黄の杖を持った人が歩いているときは、警音器を鳴らして注意しながら通行すべきである。", explanation: "子供や身体の不自由な人などが、通行しているときは、一時停止か徐行しなければなりません。", correct_answer: false)
Problem.create(question_text: "交差点や交差点の付近で、緊急自動車が近づいてきたときは、交差点を避け、道路の左側によって徐行しなければならない。", explanation: "交差点をさけて、道路の左側に寄って、一時停止をします。", correct_answer: false)
Problem.create(question_text: "同一方向に二つの車両通行帯があるときは、速い車が右側、遅い車は左側を通行するようにする。", explanation: "車両通行帯のある道路では、左側の車両通行帯を通行します。", correct_answer: false)
Problem.create(question_text: "大型特殊免許を受けている者は、普通自動車、小型特殊自動車、原動機付自転車を運転することができる。", explanation: "大型特殊免許運転できる車は、大型特殊、小型特殊、原付で普通自動車は運転できません。", correct_answer: false)
Problem.create(question_text: "車を運転するときは、疲労を避けるため身体を斜めにしたり、肘を窓枠に乗せて運転してもよい。", explanation: "運転姿勢を正しく保つことによって疲労を軽減するなどします。", correct_answer: false)
Problem.create(question_text: "標識や標示により最高速度の指定のない一般道路では、総排気量２５０ｃｃの自動二輪車の最高速度は、５０キロメートル毎時である。", explanation: "総排気量２５０ｃｃの自動二輪車の最高速度は60キロメートル毎時です。", correct_answer: false)
Problem.create(question_text: "一方通行の道路から右折するときは、あらかじめ道路の中央により交差点の中心の内側を徐行する。", explanation: "あらかじめできるだけ道路の右端により、交差点の中心の内側を徐行します。", correct_answer: false)
Problem.create(question_text: "見通しのきかない交差点やカーブでは、他の車両に注意を促すため、警音器を鳴らして通行するのもよい方法である。", explanation: "警音器は指定された場所以外はみだりに鳴らしてはいけません。", correct_answer: false)
Problem.create(question_text: "海外旅行や病気などのためやむをえない場合は、たとえ有効期間の過ぎた免許証であっても、運転免許証の更新の特例として更新手続きができる。", explanation: "有効期間の過ぎた場合は、更新手続きはできません。更新期間前であれば更新申請ができますがパスポートや診断書が必要となります。", correct_answer: false)
Problem.create(question_text: "一時停止の標識がある交差点で停止線がひかれていないときは、道路標識の直前で一時停止をしなければならない。", explanation: "停止線がない場合は、交差点の直前で一時停止します。", correct_answer: false)
Problem.create(question_text: "車はどのような場合でも、追い越しをするときには右側から追い越さなければならない。", explanation: "追い越しをするときは右側を通行しなければいけませんが、前の車が右折のため道路の中央に寄っているときは、左側を通行できます。", correct_answer: false)
Problem.create(question_text: "歩行者用道路はどんな車でも通行できるが、通行する際には歩行者などに注意して徐行しなければならない。", explanation: "通行できる車は、沿道に車庫を持つ車と特に通行を認められた車だけが通行できます。", correct_answer: false)
Problem.create(question_text: "標識・標示と警察官の手信号が違っていたので標識・標示に従った。", explanation: "危険防止や交通の安全と円滑を図るために、交通整理などしている場合は警察官の手信号に従ってください。", correct_answer: false)
Problem.create(question_text: "左側部分の幅が6メートル以上の見通しのよい道路で、右側部分にはみ出して前の車を追い越した。", explanation: "左側部分の幅が6メートル以上ある道路では、右側部分にはみ出して追い越しをしてはいけません。", correct_answer: false)
Problem.create(question_text: "通学、通園バスが子供の乗り降りのため停止していたが、バスとの間に1メートル以上の間隔がとれたのでそのまま通行した。", explanation: "通学、通園バスのそばを通るときには、徐行して安全を確かめなければなりません。", correct_answer: false)
Problem.create(question_text: "横断歩道、自転車横断帯、踏切りとその手前30メートル以内は、追い越しも追い抜きも禁止されている。", explanation: "踏み切りは、追い抜きは禁止されていません。", correct_answer: false)
Problem.create(question_text: "道路の曲がり角付近や勾配の急な下り坂は、見通しのよいときは徐行しなくてもよい。", explanation: "見通しのよい悪いに関係なく、徐行しなければなりません。", correct_answer: false)
Problem.create(question_text: "路線バス優先通行帯を普通自動車で通行中、後方から通学・通園バスが接近して来たが、路線バスではなかったのでそのまま通行した。", explanation: "後方から通学・通園バスは路線バスなどに含まれるので速やかにそこからでなければなりません。", correct_answer: false)
Problem.create(question_text: "警察官が腕を垂直に上げたときは、警察官が腕を垂直に上げる前の身体の正面に平行する交通に対面する手信号の意味は、信号機の黄色の灯火と同じ意味である。", explanation: "対面する交通についての信号の意味は赤信号です。", correct_answer: false)
Problem.create(question_text: "横断歩道に近づいたとき、進路の前方を歩行者が横断しようとしていたので、その通行を妨げないように徐行して通行した。", explanation: "横断しようとしている時は、一時停止をしてゆずらなければなりません。", correct_answer: false)
Problem.create(question_text: "二輪車のエンジンをかけたままで押して歩くときは、歩道や横断歩道を通行してもよい。", explanation: "二輪車のエンジンをとめて押して歩くと歩行者として扱われます。", correct_answer: false)
Problem.create(question_text: "子供が一人で歩いているときや、車椅子で通行している人がいるときは、安全な間隔をあけるか徐行しなければならない。", explanation: "一時停止か徐行して、安全に通行できるようにしなければなりません。", correct_answer: false)
Problem.create(question_text: "交差点、又はその付近で緊急自動車が近づいてきたときは、交差点を避け道路の左側によって、徐行しなければならない。", explanation: "交差点を避けて、道路の左側によって、一時停止をします。", correct_answer: false)
# Problem.create(question_text: ""
#   , explanation: ""
#   , correct_answer: false)


Problem.create(question_text: "同一方向に二つの車両通行帯があるときは、追い越しや右折のため以外は、左側の車輌通行帯を通行する。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "車を運転中、急用があって自動車電話や携帯電話をかける場合は、道路の左側によって停車してからかけるのがよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点で対面する信号が青色を表示しているときは、自動車、原動付自転車（二段階の右折方法により右折しようとするものを除く）は、ともに直進、左折、右折することができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自転車の側方を通るときに、安全な間隔が取れなかったので徐行して通行した。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自転車以外の車両は、自転車道を通行してはならないが、道路外の施設に出入りするためやむをえない場合は、通行することができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "見通しの悪い交差点（交通整理が行われている場合と、優先道路を通行している場合を除く）や、曲がり角を通行するときは、徐行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "横断歩道とその手前30メートル以内の場所では、追い越しが禁止されている。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "前の車のブレーキ灯（制動等）が急に明るくなったときは、その車がブレーキを踏んだと考えてよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "標識とは、交通規制などを示す表示板のことをいい本標識と補助標識がある。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自動車から降りるためドアを開けるときは、まず少し開けて一度止め、安全を確かめてから降りるようにしたほうがよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "車両通行帯のない道路では、追い越し等でやむをえない場合のほかは、自動車は道路の左側よりを通行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "運転するときの運転席のシートの前後の位置は、クラッチペダルを踏んだとき、膝がわずかに曲がる状態に合わせるのがよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点の手前で信号が黄色に変わったが、停止位置で安全に停止できなかったので、そのまま交差点を通過した。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "道路標示で黄色の表示は、ふつう特定の交通方法を禁止する意味を持っている。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "徐行や停止の合図の時期は、徐行や停止をしようとするときである。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点を右左折するときは、車の内輪差を考えて運転しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "運転者が疲れているときは、認知して判断するまでに時間がかかるので、空走距離は長くなる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "警察官又は、交通巡視員が腕を垂直に上げているとき、身体の正面に平行する交通については、信号機の黄色の灯火と同じ意味である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自動車や原動機付自転車は、自動車損害賠償責任保険（自賠責保険）か自動車損害賠償責任共済（責任共済）に加入していなければ運転することはできない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "トンネルの中に車両通行帯がある場合は、追い越しをしてもよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点付近以外のところで、緊急自動車が近づいてきたので道路の左側によって一時停止した。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自動車を運転するときは、自分の通行の利便だけを考えず、また沿道で生活している人々に対し不愉快な騒音などの迷惑をかけてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点又は、その付近以外のところで緊急自動車が近づいてきたときは、車は道路の左側によって進路をゆずらなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "エンジンを止めて二輪車（他の車をけん引している場合や側車付を除く）を押して歩くときは、歩行者と同じ通行方法でよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "他人に迷惑をかけないようにしたり、危険を与えないようにしたりして、他人を思いやる気持ちで運転することは、交通規則を守ることにつながる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "同一方向に三つ以上の通行帯があるときは、最も右側の通行帯は追い越しのためにあけておき、速度の遅い車が左側、速度が速くなるにつれて順次右側寄りの通行帯を通行する。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "優先道路を通行中であっても、横断歩道や自転車横断帯とその手前３０メートル以内では、追い越しや追い抜きをしてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "乗車定員１１人以上２９人以下の車を運転するときは、中型免許が必要である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "同一方向に二つの車両通行帯があり、特に通行区分が示されていなければ、車種に関係なく左側の通行帯を通行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "前の車が、原動機付自転車を追い越そうとしているとき、追い越しを始めた。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "見通しの悪い交差点（交通整理が行われている場合と、優先道路を通行している場合を除く）や曲がり角を通行するときは、徐行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点にさしかかったとき、緊急自動車が近づいてきたので、交差点を避けて左側によって一時停止をして道をゆずった。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "道路外に出るため右折や左折の合図をする時期は、そのしようとする地点の３０メートル手前である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "横断歩道に近づいたとき、歩行者がいるかいないかはっきりしないときは、その手前で停止できる速度で進行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "右手を水平にのばし、肘から垂直に曲げたときは、左折の合図である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "車は、交通整理が行われていない道幅が同じような道路の交差点では、左方から進行してくる車の進行を妨げてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "信号機の信号が黄色の点滅のとき、歩行者や車は他の交通に注意して進むことができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "前方の信号が赤であっても、同時に青の右向きの矢印信号が出たときは、軽車両と二段階の右折方法により右折する原動機付自転車は進むことはできない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "運転者席以外の座席にシートベルトが備えられている車では、運転者はこれを着用させる義務がある。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "二輪車を選ぶ場合、センタースタンドを立てることができること、二輪車にまたがったとき両足のつま先が地面にとどき、８の字型に押して歩くことができるものでなくてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交通整理が行われていない道幅が同じような交差点では、左方から進行してくる車が優先される。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "車は、歩行者の通行や他の車の進行を妨げるような場所では、横断、転回、後退をしてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "上り坂の頂上付近や勾配の急な下り坂は、追い越しは禁止されているが、上り坂では追い越しをしてもよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "運転者は、初心者マークを付けた車の側方に幅寄せをしたり、前方に無理に割り込むようなことをしてはならないが、急ブレーキや急ハンドルになるためやむをえない場合は別である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "交差点、横断歩道、自転車横断帯の手前３０メートル以内の場所では、追い越しや追い越しのための進路変更も禁止されている", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "普通免許で運転することのできる自動車は、普通自動車と小型特殊自動車だけである。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "原動機付自転車が交差点を右折するときは、あらかじめ道路の中央により、交差点の中心のすぐ内側を徐行しながら通行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "標識で禁止されていない場所でも、他の交通の妨害となるおそれがあるときは、横断や転回をしてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "車両通行帯のあるトンネルは、追い越しを禁止する場所ではない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "人の乗り降りのため停止しようとして徐行している車の側方を通りその前に出るような行為は、割り込み違反とはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "タイヤや路面の状態は、空走距離には関係ないが制動距離には大きく影響する。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "信号機の信号が黄色になったときは、車は原則として停止位置より先に進んではならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "徐行や停止をしようとするときの合図の時期は、徐行や停止をしようとするときである。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "転回をしようとするときは、その転回をしようとする地点から３０メートル手前で合図をする。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "横断歩道のない交差点、又はその付近を横断している歩行者がいる場合は、その通行を妨げてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "運転操作に支障がないと思っても、裸や下着で運転するのはよくない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "横断歩道に近づいたとき、歩行者がいるかいないかわからないときは、停止できるように速度を落として進まなくてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "安全地帯の側方を通るときは、歩行者がいるときに限り、徐行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "中央に黄線がひかれている道路でも、道路の右側にはみ出さなければ追い越しをしてもよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "勾配の急な上り坂は、追い越しを禁止する場所ではない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "踏切を通過しようとするときは、一時停止をしなければならないが、踏切用の信号機が青色の灯火のときはその必要がない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "坂道でがけ側を通る車は、上り下りに関係なく山側を通る車に道をゆずるのが安全である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "左右の見通しのきかない交差点では、道幅の広い狭いに関係なく徐行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "年齢が２1歳で大型免許を取得し、２年を経過した者は、車両総重量１１トンの大型貨物自動車を運転することができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "運転免許には、第一種免許、第二種免許、仮免許の三種類がある。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "座席ベルトがあるときは、運転者は原則として、後部座席の人にも座席ベルトをさせなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "トンネルの中であっても、車両通行帯があれば追い越しができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "手による合図で、右手を水平に伸ばし肘から垂直に上げたときは、左折、又は左への進路変更である。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "一方通行の道路から右折する場合には、あらかじめできるだけ道路の右端により、交差点の中心の内側を徐行しながら通行しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "前の車が、原動機付自転車を追い越そうとしていたが、その車を追い越した。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自動二輪免許では、自動二輪車、小型特殊自動車、原動機付自転車を運転することができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "タクシーやハイヤーなどを回送するときは、普通第一種免許証で運転できる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "やむを得ずバックで発進するときは、できるだけ同乗者などに安全確認を手伝ってもらうのがよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "仮免許練習標識や初心運転者標識を表示している車の側方に幅寄せをしたり、前方に無理に割り込んではならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "自動車および原動機付自転車は、必ず自動車損害賠償責任保険や自動車損害賠償責任共済に加入しなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "21歳以上で大型免許を受けていれば、運転経験に関係なく最大積載量6.5トンの大型ダンプカーに砂利を積載して運転することができる。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "横断歩道、自転車横断帯とその手前30メートル以内は、追い越したり追い抜いたりしてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "中央に黄線が引かれている場所でも、道路の右側部分にはみ出して通行しなければ、追い越しをしてもよい。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "横断歩道に近づいたとき、歩行者がいるかいないかはっきりわからないときは、その手前で停止できるように減速して進まなければならない。", explanation: "問題の通り正解です。", correct_answer: true)
Problem.create(question_text: "標識や標示で禁止されていない場所でも、他の交通の妨害となるおそれがあるときは、転回や横断をしてはならない。", explanation: "問題の通り正解です。", correct_answer: true)
# Problem.create(question_text: ""
#   , explanation: "問題の通り正解です。"
#   , correct_answer: true)
